# models.py

from sqlalchemy import Boolean, Column, ForeignKey, Integer, String, DateTime, Float
from sqlalchemy.orm import relationship

from .database import Base

class WifiCounts(Base):
    __tablename__ = "wifi_counts"

    timestamp = Column(DateTime, primary_key=True, index = True)
    Atki = Column(Integer)
    Auxi = Column(Integer)
    BaTF = Column(Integer)
    Band = Column(Integer)
    Barn = Column(Integer)
    BelG = Column(Integer)
    BelH = Column(Integer)
    Bioi = Column(Integer)
    Burs = Column(Integer)
    Cafe = Column(Integer)
    Came = Column(Integer)
    Cato = Column(Integer)
    Ceda = Column(Integer)
    CoEd = Column(Integer)
    Colv = Column(Integer)
    Cone = Column(Integer)
    Coun = Column(Integer)
    Denn = Column(Integer)
    Duke = Column(Integer)
    EPIC = Column(Integer)
    FOPS = Column(Integer)
    Faci = Column(Integer)
    Foun = Column(Integer)
    Fret = Column(Integer)
    Frid = Column(Integer)
    Gage = Column(Integer)
    Gari = Column(Integer)
    Grig = Column(Integer)
    Harr = Column(Integer)
    Heal = Column(Integer)
    Hick = Column(Integer)
    Hous = Column(Integer)
    HunH = Column(Integer)
    Irwi = Column(Integer)
    JBui = Column(Integer)
    Kenn = Column(Integer)
    King = Column(Integer)
    Laur = Column(Integer)
    Levi = Column(Integer)
    Lync = Column(Integer)
    MSII = Column(Integer)
    Macy = Column(Integer)
    Mart = Column(Integer)
    McCo = Column(Integer)
    McMi = Column(Integer)
    Memo = Column(Integer)
    MilH = Column(Integer)
    Milt = Column(Integer)
    NERF = Column(Integer)
    PORT = Column(Integer)
    Phil = Column(Integer)
    Pros = Column(Integer)
    Rece = Column(Integer)
    Rees = Column(Integer)
    Robi = Column(Integer)
    Rowe = Column(Integer)
    SVDH = Column(Integer)
    Scot = Column(Integer)
    Smit = Column(Integer)
    SoTF = Column(Integer)
    Stor = Column(Integer)
    StuA = Column(Integer)
    StuH = Column(Integer)
    StuU = Column(Integer)
    Syca = Column(Integer)
    Tenn = Column(Integer)
    UREC = Column(Integer)
    Unio = Column(Integer)
    Wach = Column(Integer)
    Wall = Column(Integer)
    Winn = Column(Integer)
    With = Column(Integer)
    Wood = Column(Integer)

class Buildings(Base):
    __tablename__ = "buildings"

    abbreviation = Column(String, index = True)
    name = Column(String, index = True)
    id = Column(Integer, index = True, primary_key = True)
    latitude = Column(Float, index = True)
    longitude = Column(Float, index = True)